### ISSUE TITLE
Can't find icon that exists in icons

### ISSUE THREAD

**Issue by ryanabx** [oknozor/freedesktop-icons#20]
I have this code:

```rust
let icon_path = freedesktop_icons::lookup("text-x-script")
            .with_cache()
            .find()
            .unwrap();
```

And a path to an icon I know exists:
`/usr/share/icons/AdwaitaLegacy/48x48/mimetypes/text-x-script.png`

But I get an `Option::unwrap()' on a 'None' value` error

What am I missing here?

**Comment by oknozor** [comment]
You need to specify a theme, there is no global icon lookup in this crate.
```rust
        let icon_path = lookup("text-x-script")
            .with_theme("AdwaitaLegacy")
            .with_cache()
            .find()
            .unwrap();
```

**Comment by ryanabx** [comment]
Ah, that's unfortunate, but probably for performance reasons might make sense.

Perhaps a way to specify searching in all themes would be nice

**Comment by oknozor** [comment]
I don't see why you would want to do that.

**Comment by ryanabx** [comment]
Maybe I'm using this crate wrong, or what I'm asking for is accomplished in a different way.

I want to access symbolic icons (for example, `network-wireless-connected-75-symbolic`), and multiple themes may have those icons. I don't want to specify a theme because I want it to be able to fall back to other themes if needed.

I can try to make this functionality myself within my program, but I don't know if this is the expected way to work with symbolic icons in the first place

**Comment by oknozor** [comment]
The whole point of having icon themes is to have a set of icons that share a common look and feel. I understand the temptation of falling back to any theme when an icon is not found. But this is not the way this is intended to work. 

Either your base theme has the icons you are looking for, or we fallback to the parent theme, in last resort we use the generic icons from "hicolor" theme.

If you really need to find icons regardless of the theme, you don't need the freedesktop icon implementation at all.

**Comment by ryanabx** [comment]
Thanks, that's actually really informative!
