### ISSUE TITLE
Merge themes of same name in different directories

### ISSUE THREAD

**Issue by Drakulix** [oknozor/freedesktop-icons#7]
Currently [`get_all_themes`](https://github.com/oknozor/freedesktop-icons/blob/main/src/theme/mod.rs#L143) [overrides](https://github.com/oknozor/freedesktop-icons/blob/main/src/theme/mod.rs#L150) icon themes already present in the `THEMES` directory.

This is not correct, as users might override parts of a theme in their `.local/share/icons` folder. Additionally tools like `flatpak` extend the `XDG_DATA_DIRS` environment variable and provide application icons by extending the `hicolor` theme.

I would suggest `THEMES` value type to be of type `Vec<Theme>` instead and let lookup function test each of the returned themes of the same name. Would there be interest in a PR, that does this?

**Comment by oknozor** [comment]
Of course, please make a PR :)
